sonar.projectKey=josevmorilla_digital-portfolio
sonar.organization=josevmorilla

sonar.sources=backend/src,frontend/src
sonar.tests=backend/__tests__,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info,frontend/coverage/lcov.info

sonar.coverage.exclusions=\
  backend/prisma/**,\
  backend/fix-migrations.mjs,\
  frontend/src/test/**,\
  frontend/src/main.jsx,\
  **/*.config.js

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  uploads/**
